spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

poi:
  fetch:
    onstartup: false

course:
  seed:
    gpx:
      onstartup: false

logging:
  level:
    com.bikeoasis: INFO
