server {
    listen 80;
    server_name _;

    client_max_body_size 20m;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /api/ {
        include /etc/nginx/conf.d/active-backend.conf;
    }

    location /ws-stomp {
        include /etc/nginx/conf.d/active-backend.conf;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 3600;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
